// GlobalUsings.cs

// Project Usings
global using Fatagram.API.Authentication;
global using Fatagram.Application;
global using Fatagram.Application.Common;
global using Fatagram.Application.Services.AuthServices;
global using Fatagram.Application.Services.AuthServices.Interface;
global using Fatagram.Application.Services.AuthServices.OAuth;
global using Fatagram.Application.Services.ImageService;
global using Fatagram.Application.Services.ImageService.Interface;
global using Fatagram.Application.Services.JwtServices;
global using Fatagram.Application.Services.JwtServices.Interface;
global using Fatagram.Application.Services.NotificationServices;
global using Fatagram.Application.Services.NotificationServices.Interface;
global using Fatagram.Application.Services.NotificationServices.Interfaces;
global using Fatagram.Application.Services.TokenServices;
global using Fatagram.Application.Services.TokenServices.Interface;
global using Fatagram.Application.Services.UserServices.FriendshipServices;
global using Fatagram.Application.Services.UserServices.FriendshipServices.Interface;
global using Fatagram.Application.Services.UserServices.UserConfigServices;
global using Fatagram.Application.Services.UserServices.UserConfigServices.Interfaces;
global using Fatagram.Application.Services.UserServices.UserProfileServices;
global using Fatagram.Application.Services.UserServices.UserProfileServices.Interfaces;
global using Fatagram.Infrastructure.Data;
global using Fatagram.Infrastructure.Repositories.AccountRepository;
global using Fatagram.Infrastructure.Repositories.AccountRepository.Interface;
global using Fatagram.Infrastructure.Repositories.FriendRequestRepository;
global using Fatagram.Infrastructure.Repositories.FriendRequestRepository.Interfaces;
global using Fatagram.Infrastructure.Repositories.FriendshipRepository;
global using Fatagram.Infrastructure.Repositories.FriendshipRepository.Interfaces;
global using Fatagram.Infrastructure.Repositories.NotificationRepository;
global using Fatagram.Infrastructure.Repositories.NotificationRepository.Interface;
global using Fatagram.Infrastructure.Repositories.RefreshTokenRepository;
global using Fatagram.Infrastructure.Repositories.RefreshTokenRepository.Interface;
global using Fatagram.Infrastructure.Repositories.UserRepository;
global using Fatagram.Infrastructure.Repositories.UserRepository.Interface;
// Framework Usings
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
