// GlobalUsings.cs

// Project Usings
global using Fatagram.API.Authentication;
global using Fatagram.Application;
global using Fatagram.Application.Common;
global using Fatagram.Application.Services.AuthServices;
global using Fatagram.Application.Services.AuthServices.OAuth;
global using Fatagram.Application.Abstractions.Storage;
global using Fatagram.Application.Services.JwtServices;
global using Fatagram.Application.Services.NotificationServices;
global using Fatagram.Application.Services.TokenServices;
global using Fatagram.Application.Services.UserServices.FriendshipServices;
global using Fatagram.Application.Services.UserServices.UserConfigServices;
global using Fatagram.Application.Services.UserServices.UserProfileServices;
global using Fatagram.Infrastructure.Data;
global using Fatagram.Infrastructure.Repositories.AccountRepository;
global using Fatagram.Infrastructure.Repositories.FriendRequestRepository;
global using Fatagram.Infrastructure.Repositories.FriendshipRepository;
global using Fatagram.Infrastructure.Repositories.NotificationRepository;
global using Fatagram.Infrastructure.Repositories.RefreshTokenRepository;
global using Fatagram.Infrastructure.Repositories.UserRepository;
global using Fatagram.Application.Abstractions.Repositories;
global using Fatagram.Application.Abstractions.Cache;
global using Fatagram.Application.Common.Projections;
global using Fatagram.Application.Abstractions.Security;
global using Fatagram.Infrastructure.Security;
global using Fatagram.Infrastructure.Storage;
// Framework Usings
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
