version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: fatagram_db 
    environment:
      POSTGRES_DB: fatagram
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: FatPro@123
    ports:
        - "5432:5432"
    volumes:
        - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
