// <auto-generated />
using System;
using System.Collections.Generic;
using Fatagram.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Fatagram.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820082201_AddChatThemeTable")]
    partial class AddChatThemeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fatagram.Domain.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("username");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Fatagram.Domain.Models.ChatTheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BgImage")
                        .HasColumnType("text")
                        .HasColumnName("bg_image");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(100)")
                        .HasDefaultValue("General")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DarkColorsJson")
                        .HasColumnType("text")
                        .HasColumnName("dark_colors_json");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<bool>("IsEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_event");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("label");

                    b.Property<string>("LightColorsJson")
                        .HasColumnType("text")
                        .HasColumnName("light_colors_json");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("chat_themes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Category = "General",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            IsEvent = false,
                            Key = "default",
                            Label = "Mặc định",
                            SortOrder = 0,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Category = "General",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#0f766e] to-[#34d399]\",\"primaryLight\":\"#34d399\",\"primaryMain\":\"#10b981\",\"bgMain\":\"#0a1812\",\"bgSecond\":\"#0f2019\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-emerald",
                            Label = "Emerald",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#107a51] to-[#85e3ad]\",\"primaryLight\":\"#85e3ad\",\"primaryMain\":\"#107a51\",\"bgMain\":\"#f0f8f5\",\"bgSecond\":\"#d7f0e4\"}",
                            SortOrder = 1,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Category = "General",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#9a3412] to-[#f97316]\",\"primaryLight\":\"#f97316\",\"primaryMain\":\"#ea580c\",\"bgMain\":\"#18100c\",\"bgSecond\":\"#201611\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-sunset",
                            Label = "Sunset",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#f26c4f] to-[#ffd700]\",\"primaryLight\":\"#ffd700\",\"primaryMain\":\"#f26c4f\",\"bgMain\":\"#fff8f3\",\"bgSecond\":\"#ffe4d2\"}",
                            SortOrder = 2,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            BgImage = "/images/cyberpunk_bg.png",
                            Category = "Special",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#ff007f] to-[#00f2fe]\",\"primaryLight\":\"#00f2fe\",\"primaryMain\":\"#ff007f\",\"bgMain\":\"#12101a\",\"bgSecond\":\"#191624\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-cyberpunk",
                            Label = "Cyberpunk",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#db2777] to-[#06b6d4]\",\"primaryLight\":\"#06b6d4\",\"primaryMain\":\"#db2777\",\"bgMain\":\"#fdf4ff\",\"bgSecond\":\"#f5e5fa\"}",
                            SortOrder = 3,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            Category = "General",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#6d28d9] to-[#c4b5fd]\",\"primaryLight\":\"#c4b5fd\",\"primaryMain\":\"#8b5cf6\",\"bgMain\":\"#0f0d16\",\"bgSecond\":\"#15121e\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-lavender",
                            Label = "Lavender",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#7255de] to-[#c4b5fd]\",\"primaryLight\":\"#c4b5fd\",\"primaryMain\":\"#7255de\",\"bgMain\":\"#f8f6fe\",\"bgSecond\":\"#e6e0f8\"}",
                            SortOrder = 4,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            Category = "General",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#0369a1] to-[#38bdf8]\",\"primaryLight\":\"#38bdf8\",\"primaryMain\":\"#0284c7\",\"bgMain\":\"#08121a\",\"bgSecond\":\"#0c1a26\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-ocean",
                            Label = "Ocean Deep",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#0e74b5] to-[#90e0ef]\",\"primaryLight\":\"#90e0ef\",\"primaryMain\":\"#0e74b5\",\"bgMain\":\"#f2f8fc\",\"bgSecond\":\"#d7ebf8\"}",
                            SortOrder = 5,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000007"),
                            Category = "General",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#be185d] to-[#f472b6]\",\"primaryLight\":\"#f472b6\",\"primaryMain\":\"#db2777\",\"bgMain\":\"#180c12\",\"bgSecond\":\"#221018\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-bubblegum",
                            Label = "Bubblegum",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#ec4887] to-[#fbcfe8]\",\"primaryLight\":\"#fbcfe8\",\"primaryMain\":\"#ec4887\",\"bgMain\":\"#fef6f8\",\"bgSecond\":\"#f9dce6\"}",
                            SortOrder = 6,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000008"),
                            BgImage = "/images/worldcup_bg.png",
                            Category = "Event",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#166534] to-[#22c55e]\",\"primaryLight\":\"#22c55e\",\"primaryMain\":\"#15803d\",\"bgMain\":\"#0a1812\",\"bgSecond\":\"#0f2019\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = true,
                            Key = "chat-worldcup",
                            Label = "World Cup",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#15803d] to-[#4ade80]\",\"primaryLight\":\"#4ade80\",\"primaryMain\":\"#15803d\",\"bgMain\":\"#f0f8f5\",\"bgSecond\":\"#d7f0e4\"}",
                            SortOrder = 7,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000009"),
                            BgImage = "/images/vietnam_bg.png",
                            Category = "Special",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#991b1b] to-[#ffcd00]\",\"primaryLight\":\"#ffcd00\",\"primaryMain\":\"#da251d\",\"bgMain\":\"#180a0a\",\"bgSecond\":\"#240f0f\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-vietnam",
                            Label = "Việt Nam",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#da251d] to-[#ffcd00]\",\"primaryLight\":\"#ffcd00\",\"primaryMain\":\"#da251d\",\"bgMain\":\"#fef2f2\",\"bgSecond\":\"#fee2e2\"}",
                            SortOrder = 8,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000010"),
                            BgImage = "/images/vutru_bg.png",
                            Category = "Special",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#312e81] to-[#831843]\",\"primaryLight\":\"#831843\",\"primaryMain\":\"#4c1d95\",\"bgMain\":\"#0a0718\",\"bgSecond\":\"#100c24\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-vutru",
                            Label = "Vũ trụ",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#6366f1] to-[#ec4899]\",\"primaryLight\":\"#ec4899\",\"primaryMain\":\"#8b5cf6\",\"bgMain\":\"#f5f3ff\",\"bgSecond\":\"#ede9fe\"}",
                            SortOrder = 9,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000011"),
                            BgImage = "/images/halloween_bg.png",
                            Category = "Seasonal",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#3b0764] to-[#f97316]\",\"primaryLight\":\"#f97316\",\"primaryMain\":\"#a855f7\",\"bgMain\":\"#090212\",\"bgSecond\":\"#140526\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = true,
                            Key = "chat-halloween",
                            Label = "Halloween",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#7c2d12] to-[#c2410c]\",\"primaryLight\":\"#f97316\",\"primaryMain\":\"#c2410c\",\"bgMain\":\"#fff7ed\",\"bgSecond\":\"#ffedd5\"}",
                            SortOrder = 10,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000012"),
                            BgImage = "/images/christmas_bg.png",
                            Category = "Seasonal",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#14532d] to-[#b91c1c]\",\"primaryLight\":\"#b91c1c\",\"primaryMain\":\"#16a34a\",\"bgMain\":\"#180404\",\"bgSecond\":\"#260808\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = true,
                            Key = "chat-christmas",
                            Label = "Giáng sinh",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#991b1b] to-[#f59e0b]\",\"primaryLight\":\"#f59e0b\",\"primaryMain\":\"#b91c1c\",\"bgMain\":\"#fef2f2\",\"bgSecond\":\"#fee2e2\"}",
                            SortOrder = 11,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000013"),
                            BgImage = "/images/summer_bg.png",
                            Category = "Seasonal",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#0369a1] to-[#ca8a04]\",\"primaryLight\":\"#facc15\",\"primaryMain\":\"#0284c7\",\"bgMain\":\"#06101e\",\"bgSecond\":\"#0a192e\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = true,
                            Key = "chat-summer",
                            Label = "Mùa hè",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#0284c7] to-[#f59e0b]\",\"primaryLight\":\"#38bdf8\",\"primaryMain\":\"#f59e0b\",\"bgMain\":\"#f0f9ff\",\"bgSecond\":\"#e0f2fe\"}",
                            SortOrder = 12,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000014"),
                            BgImage = "/images/cr7_bg.png",
                            Category = "Event",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#052e16] to-[#eab308]\",\"primaryLight\":\"#eab308\",\"primaryMain\":\"#16a34a\",\"bgMain\":\"#021008\",\"bgSecond\":\"#052010\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = true,
                            Key = "chat-cr7",
                            Label = "CR7",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#15803d] to-[#facc15]\",\"primaryLight\":\"#facc15\",\"primaryMain\":\"#15803d\",\"bgMain\":\"#f0fdf4\",\"bgSecond\":\"#dcfce7\"}",
                            SortOrder = 13,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000015"),
                            Category = "General",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#1e053a] to-[#db2777]\",\"primaryLight\":\"#db2777\",\"primaryMain\":\"#8b5cf6\",\"bgMain\":\"#0d0515\",\"bgSecond\":\"#160a22\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-midnight",
                            Label = "Midnight Blossom",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#2e0854] to-[#f472b6]\",\"primaryLight\":\"#f472b6\",\"primaryMain\":\"#2e0854\",\"bgMain\":\"#faf5ff\",\"bgSecond\":\"#f3e8ff\"}",
                            SortOrder = 14,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000016"),
                            Category = "Seasonal",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#78350f] to-[#f59e0b]\",\"primaryLight\":\"#f59e0b\",\"primaryMain\":\"#d97706\",\"bgMain\":\"#170f0a\",\"bgSecond\":\"#22160f\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-autumn",
                            Label = "Golden Autumn",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#b45309] to-[#fcd34d]\",\"primaryLight\":\"#fcd34d\",\"primaryMain\":\"#b45309\",\"bgMain\":\"#fffbeb\",\"bgSecond\":\"#fef3c7\"}",
                            SortOrder = 15,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000017"),
                            Category = "General",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#075985] to-[#38bdf8]\",\"primaryLight\":\"#38bdf8\",\"primaryMain\":\"#0284c7\",\"bgMain\":\"#08131a\",\"bgSecond\":\"#0c1d29\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-glacier",
                            Label = "Frosty Glacier",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#0369a1] to-[#e0f2fe]\",\"primaryLight\":\"#38bdf8\",\"primaryMain\":\"#0369a1\",\"bgMain\":\"#f0f9ff\",\"bgSecond\":\"#e0f2fe\"}",
                            SortOrder = 16,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000018"),
                            Category = "General",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#020617] to-[#22c55e]\",\"primaryLight\":\"#22c55e\",\"primaryMain\":\"#10b981\",\"bgMain\":\"#050814\",\"bgSecond\":\"#0b1021\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-neon",
                            Label = "Neon Oasis",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#0f172a] to-[#10b981]\",\"primaryLight\":\"#10b981\",\"primaryMain\":\"#0f172a\",\"bgMain\":\"#f8fafc\",\"bgSecond\":\"#f1f5f9\"}",
                            SortOrder = 17,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000019"),
                            Category = "General",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#9f1239] to-[#fb7185]\",\"primaryLight\":\"#fb7185\",\"primaryMain\":\"#e11d48\",\"bgMain\":\"#180b0e\",\"bgSecond\":\"#241014\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-rose",
                            Label = "Rose Quartz",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#be123c] to-[#ffe4e6]\",\"primaryLight\":\"#fb7185\",\"primaryMain\":\"#be123c\",\"bgMain\":\"#fff1f2\",\"bgSecond\":\"#ffe4e6\"}",
                            SortOrder = 18,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000020"),
                            Category = "General",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#14532d] to-[#4ade80]\",\"primaryLight\":\"#4ade80\",\"primaryMain\":\"#16a34a\",\"bgMain\":\"#09140e\",\"bgSecond\":\"#0e1f15\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-forest",
                            Label = "Forest Mist",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#166534] to-[#dcfce7]\",\"primaryLight\":\"#4ade80\",\"primaryMain\":\"#166534\",\"bgMain\":\"#f0fdf4\",\"bgSecond\":\"#dcfce7\"}",
                            SortOrder = 19,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000021"),
                            Category = "General",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#172554] to-[#eab308]\",\"primaryLight\":\"#eab308\",\"primaryMain\":\"#ca8a04\",\"bgMain\":\"#060b18\",\"bgSecond\":\"#0a1226\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-royal",
                            Label = "Royal Amber",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#1e3a8a] to-[#fef08a]\",\"primaryLight\":\"#facc15\",\"primaryMain\":\"#1e3a8a\",\"bgMain\":\"#eff6ff\",\"bgSecond\":\"#dbeafe\"}",
                            SortOrder = 20,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000022"),
                            Category = "General",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#312e81] to-[#ec4899]\",\"primaryLight\":\"#ec4899\",\"primaryMain\":\"#d946ef\",\"bgMain\":\"#090816\",\"bgSecond\":\"#0e0d24\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-tokyo",
                            Label = "Tokyo Drift",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#4f46e5] to-[#f472b6]\",\"primaryLight\":\"#f472b6\",\"primaryMain\":\"#4f46e5\",\"bgMain\":\"#eef2ff\",\"bgSecond\":\"#e0e7ff\"}",
                            SortOrder = 21,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000023"),
                            Category = "General",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#365314] to-[#a3e635]\",\"primaryLight\":\"#a3e635\",\"primaryMain\":\"#84cc16\",\"bgMain\":\"#0e1507\",\"bgSecond\":\"#16220b\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-matcha",
                            Label = "Matcha Latte",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#3f6212] to-[#d9f99d]\",\"primaryLight\":\"#a3e635\",\"primaryMain\":\"#3f6212\",\"bgMain\":\"#f7fee7\",\"bgSecond\":\"#ecfccb\"}",
                            SortOrder = 22,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000024"),
                            Category = "General",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DarkColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#9d174d] to-[#f472b6]\",\"primaryLight\":\"#f472b6\",\"primaryMain\":\"#db2777\",\"bgMain\":\"#1c0d14\",\"bgSecond\":\"#2a131e\"}",
                            IsActive = true,
                            IsDefault = false,
                            IsEvent = false,
                            Key = "chat-sakura",
                            Label = "Sakura Cherry",
                            LightColorsJson = "{\"gradient\":\"bg-gradient-to-tr from-[#db2777] to-[#fdf2f8]\",\"primaryLight\":\"#f472b6\",\"primaryMain\":\"#db2777\",\"bgMain\":\"#fff5f7\",\"bgSecond\":\"#ffe4e6\"}",
                            SortOrder = 23,
                            Version = 0u
                        });
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("BackgroundUrl")
                        .HasColumnType("text")
                        .HasColumnName("background_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_group");

                    b.Property<int>("LastMessageNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_message_number");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("name");

                    b.Property<string>("SearchText")
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(search_text, ''))", true);

                    b.Property<string>("Theme")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("theme");

                    b.Property<string>("UniqueConversationKey")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("unique_conversation_key");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SearchText");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("UniqueConversationKey")
                        .IsUnique();

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("Fatagram.Domain.Models.ConversationParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("LastSeenMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_seen_message_id");

                    b.Property<int>("LastSeenNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_seen_number");

                    b.Property<string>("Nickname")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("nickname");

                    b.Property<DateTime?>("PinnedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("pinned_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("SeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("seen_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenMessageId");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "UserId")
                        .IsUnique();

                    b.ToTable("conversation_participants", (string)null);
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("emails", (string)null);
                });

            modelBuilder.Entity("Fatagram.Domain.Models.FriendRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("friend_requests", (string)null);
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("friendships", (string)null);
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3bb9f4e-1d6e-4f4a-9f7a-2c3b5e6d7f8a"),
                            Code = "en",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "English",
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("c4cc9f4e-2d7e-5f5a-0f8a-3d4c6f7e8f9b"),
                            Code = "vi",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Vietnamese",
                            Version = 0u
                        });
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Localized", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("language_code");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("LocalizationKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("localization_key");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("localizeds", (string)null);
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Dictionary<string, object>>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("read_at");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<int>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sequence_number");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.HasIndex("ConversationId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Fatagram.Domain.Models.MessageMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("IndexInMessage")
                        .HasColumnType("integer")
                        .HasColumnName("index_in_message");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("MessageSequence")
                        .HasColumnType("integer")
                        .HasColumnName("message_sequence");

                    b.Property<Dictionary<string, object>>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("message_media", (string)null);
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer")
                        .HasColumnName("actor_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer")
                        .HasColumnName("target_type");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("notification_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Access conversation resources as a member",
                            Name = "conversation.member",
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modify own user resources",
                            Name = "user.owner",
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Access admin panel",
                            Name = "admin.access",
                            Version = 0u
                        });
                });

            modelBuilder.Entity("Fatagram.Domain.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System administrator",
                            IsSystem = true,
                            Name = "Admin",
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Regular user",
                            IsSystem = true,
                            Name = "User",
                            Version = 0u
                        });
                });

            modelBuilder.Entity("Fatagram.Domain.Models.RoutePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(10)")
                        .HasDefaultValue("*")
                        .HasColumnName("http_method");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("permission_name");

                    b.Property<string>("ResourceParam")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("resource_param");

                    b.Property<string>("RoutePattern")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("route_pattern");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("HttpMethod", "RoutePattern")
                        .IsUnique();

                    b.ToTable("route_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HttpMethod = "*",
                            IsActive = true,
                            Order = 10,
                            PermissionName = "conversation.member",
                            ResourceParam = "conversationId",
                            RoutePattern = "api/v1/conversations/{conversationId}/messages",
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HttpMethod = "*",
                            IsActive = true,
                            Order = 20,
                            PermissionName = "conversation.member",
                            ResourceParam = "conversationId",
                            RoutePattern = "api/v1/conversations/{conversationId}/*",
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HttpMethod = "PUT",
                            IsActive = true,
                            Order = 10,
                            PermissionName = "user.owner",
                            ResourceParam = "userId",
                            RoutePattern = "api/v1/users/{userId}",
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HttpMethod = "DELETE",
                            IsActive = true,
                            Order = 20,
                            PermissionName = "user.owner",
                            ResourceParam = "userId",
                            RoutePattern = "api/v1/users/{userId}",
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HttpMethod = "*",
                            IsActive = true,
                            Order = 1,
                            PermissionName = "admin.access",
                            RoutePattern = "api/v1/admin/*",
                            Version = 0u
                        });
                });

            modelBuilder.Entity("Fatagram.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar");

                    b.Property<string>("Background")
                        .HasColumnType("TEXT")
                        .HasColumnName("background");

                    b.Property<Dictionary<string, object>>("BackgroundMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("bg_metadata");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("DATE")
                        .HasColumnName("birth_day");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("full_name");

                    b.Property<int?>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<bool>("IsOnBoarding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasDefaultValue(false)
                        .HasColumnName("is_on_boarding");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(10)")
                        .HasDefaultValue("en")
                        .HasColumnName("language_code");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Nickname")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("nickname");

                    b.Property<string>("Phone")
                        .HasColumnType("VARCHAR(15)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UrlName")
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("url_name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Fatagram.Domain.Models.UserEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmailId")
                        .HasColumnType("uuid")
                        .HasColumnName("email_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EmailId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("is_primary = true");

                    b.ToTable("user_emails", (string)null);
                });

            modelBuilder.Entity("Fatagram.Domain.Models.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId", "NotificationId")
                        .IsUnique();

                    b.ToTable("user_notifications", (string)null);
                });

            modelBuilder.Entity("Fatagram.Domain.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId", "ResourceId")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionsId = new Guid("20000000-0000-0000-0000-000000000003"),
                            RolesId = new Guid("10000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Account", b =>
                {
                    b.HasOne("Fatagram.Domain.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.ConversationParticipant", b =>
                {
                    b.HasOne("Fatagram.Domain.Models.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fatagram.Domain.Models.Message", "LastSeenMessage")
                        .WithMany()
                        .HasForeignKey("LastSeenMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fatagram.Domain.Models.User", "User")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("LastSeenMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.FriendRequest", b =>
                {
                    b.HasOne("Fatagram.Domain.Models.User", "Receiver")
                        .WithMany("FriendRequestsReceived")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fatagram.Domain.Models.User", "Sender")
                        .WithMany("FriendRequests")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Friendship", b =>
                {
                    b.HasOne("Fatagram.Domain.Models.User", "User1")
                        .WithMany("FriendshipAsUser1")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fatagram.Domain.Models.User", "User2")
                        .WithMany("FriendshipAsUser2")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Localized", b =>
                {
                    b.HasOne("Fatagram.Domain.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Message", b =>
                {
                    b.HasOne("Fatagram.Domain.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fatagram.Domain.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.MessageMedia", b =>
                {
                    b.HasOne("Fatagram.Domain.Models.Message", "Message")
                        .WithMany("Media")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("Fatagram.Domain.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.User", b =>
                {
                    b.HasOne("Fatagram.Domain.Models.Language", "Language")
                        .WithMany("Users")
                        .HasForeignKey("LanguageCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.UserEmail", b =>
                {
                    b.HasOne("Fatagram.Domain.Models.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fatagram.Domain.Models.User", "User")
                        .WithMany("UserEmails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.UserNotification", b =>
                {
                    b.HasOne("Fatagram.Domain.Models.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fatagram.Domain.Models.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.UserRole", b =>
                {
                    b.HasOne("Fatagram.Domain.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fatagram.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("Fatagram.Domain.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fatagram.Domain.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Language", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Message", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Notification", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Fatagram.Domain.Models.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("ConversationParticipants");

                    b.Navigation("FriendRequests");

                    b.Navigation("FriendRequestsReceived");

                    b.Navigation("FriendshipAsUser1");

                    b.Navigation("FriendshipAsUser2");

                    b.Navigation("Messages");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserEmails");

                    b.Navigation("UserNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
